[package]
name = "rust-advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.66"
lazy_static = "1.4.0"
num-bigint = "0.4.3"
regex = "1.7.1"
